### ISSUE TITLE
CSS for Login and Create an Account Page - done

### ISSUE THREAD

**Issue by Lucas22368** [cse110-fa22-group7/cse110-fa22-group7-project#28]

**Comment by bkim9** [comment]
![Image](https://user-images.githubusercontent.com/42848886/201558764-638c2257-3973-4eb3-ba01-59581db1eb91.PNG)
![Image](https://user-images.githubusercontent.com/42848886/201558765-8ab237f6-062d-40f9-b89e-b1fb2c984f5a.PNG)

Please let me know if more work to be done on it
